pipeline {
    agent any

    parameters {
        booleanParam(name: 'DESTROY_AND_REBUILD', defaultValue: true, description: 'terraform destroy, then full fresh rebuild')
        booleanParam(name: 'REBUILD_IMAGE', defaultValue: false, description: 'Rebuild the Packer image first, else reuse')
    }

    environment {
        // Securely pull the vault password from Jenkins Credentials
        ANSIBLE_VAULT_PASS = credentials('ANSIBLE_VAULT_PASS')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                // Wipe the workspace but EXCLUDE the heavy Packer golden image AND the Terraform state files so we can reuse them!
                cleanWs(deleteDirs: true, patterns: [[pattern: 'packer/output/**', type: 'EXCLUDE'], [pattern: 'terraform/*.tfstate*', type: 'EXCLUDE'], [pattern: 'terraform/.terraform/**', type: 'EXCLUDE']])
                // Pull the latest code again
                checkout scm
            }
        }

        stage('Packer') {
            when {
                expression { params.REBUILD_IMAGE == true }
            }
            steps {
                dir('packer') {
                    sh 'packer init .'
                    sh 'packer build -force almalinux.pkr.hcl'
                }
            }
        }

        stage('Terraform') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    script {
                        if (params.DESTROY_AND_REBUILD == true) {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Ansible') {
            steps {
                dir('ansible') {
                    // Temporarily inject the secret Jenkins password into a file so Ansible can read it
                    sh 'echo "$ANSIBLE_VAULT_PASS" > vaultpass.txt'
                    
                    // Jenkins user doesn't have the role installed, so we must download it first!
                    sh 'ansible-galaxy install -r requirements.yml'
                    
                    // Run the CIS Hardening Script
                    sh 'ansible-playbook playbook.yml --vault-password-file vaultpass.txt -e "rhel10cis_pass_max_days=30" --skip-tags "level2-server,level2-workstation"'
                    
                    // Delete the password file immediately after for security!
                    sh 'rm vaultpass.txt'
                }
            }
        }
        
        stage('Audit') {
            steps {
                dir('ansible') {
                    // Collect the JSON audit reports generated by Ansible
                    archiveArtifacts artifacts: '*.json', allowEmptyArchive: true
                }
            }
        }
    }
}
