pipeline {
    agent any

    parameters {
        choice(name: 'ACTION', choices: ['ALL', 'SKIP_PACKER', 'PACKER_ONLY', 'TERRAFORM_ONLY', 'ANSIBLE_ONLY'], description: 'Select which stages of the pipeline to run.')
    }

    environment {
        // Securely pull the vault password from Jenkins Credentials
        ANSIBLE_VAULT_PASS = credentials('ANSIBLE_VAULT_PASS')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                // Wipe the workspace but EXCLUDE the heavy Packer golden image AND the Terraform state files so we can reuse them!
                cleanWs(deleteDirs: true, patterns: [[pattern: 'packer/output/**', type: 'EXCLUDE'], [pattern: 'terraform/*.tfstate*', type: 'EXCLUDE'], [pattern: 'terraform/.terraform/**', type: 'EXCLUDE']])
                // Pull the latest code again
                checkout scm
            }
        }

        stage('Packer') {
            when {
                expression { params.ACTION == 'ALL' || params.ACTION == 'PACKER_ONLY' }
            }
            steps {
                dir('packer') {
                    sh 'packer init .'
                    sh 'packer build -force almalinux.pkr.hcl'
                }
            }
        }

        stage('Terraform') {
            when {
                expression { params.ACTION == 'ALL' || params.ACTION == 'SKIP_PACKER' || params.ACTION == 'TERRAFORM_ONLY' }
            }
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform destroy -auto-approve'
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Ansible') {
            when {
                expression { params.ACTION == 'ALL' || params.ACTION == 'SKIP_PACKER' || params.ACTION == 'ANSIBLE_ONLY' }
            }
            steps {
                dir('ansible') {
                    // Temporarily inject the secret Jenkins password into a file so Ansible can read it
                    sh 'echo "$ANSIBLE_VAULT_PASS" > vaultpass.txt'
                    
                    // Jenkins user doesn't have the role installed, so we must download it first!
                    sh 'ansible-galaxy install -r requirements.yml'
                    
                    // Run the CIS Hardening Script
                    sh 'ansible-playbook playbook.yml --vault-password-file vaultpass.txt -e "@group_vars/all.yml" -e "rhel10cis_pass_max_days=90"'
                    
                    // Delete the password file immediately after for security!
                    sh 'rm vaultpass.txt'
                }
            }
        }
        
        stage('Audit') {
            when {
                expression { params.ACTION == 'ALL' || params.ACTION == 'SKIP_PACKER' || params.ACTION == 'ANSIBLE_ONLY' }
            }
            steps {
                dir('ansible') {
                    // Collect the JSON audit reports generated by Ansible
                    archiveArtifacts artifacts: '*.json', allowEmptyArchive: true
                }
            }
        }
    }
}
