---
# 1. Ensure Goss auditing runs after the script finishes
setup_audit: true
run_audit: true

# 2. Tell the CIS script to use journald for logging
rhel10cis_syslog: journald

# 3. Tell the CIS script to use a custom authselect profile
rhel10cis_authselect_custom_profile_name: custom_pair_b_profile

# 4. Fix NoneType bug in CIS script
rhel10cis_sshd_allowusers: ""
