---
- name: Hardening Pair B Nodes
  hosts: all
  become: true

  # PRECEDENCE LEVEL 2: Playbook VARs ovverides group_vars
  vars:
    # We turn this rule OFF so the CIS script doesn't accidentally lock out
    # our root account and break our automated pipeline
    rhel10cis_rule_5_4_2: false
    rhel10cis_rule_5_1_20: false

  # FORMAT DATA DISKS (Task Constraint)
  pre_tasks:
    - name: Format the first 2GB data disk (sda) to ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sda
    - name: Format the second 2GB data disk (sdb) to ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb

  # EXECUTE CIS HARDENING
  roles:
    - RHEL10-CIS
